name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"] # Asegúrate de que tu rama principal sea main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject API URL
        run: |
          sed -i "s|API_URL_PLACEHOLDER|${{ secrets.HF_API_URL }}|g" script.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Sube la raíz del proyecto
          branch: gh-pages # Se creará una rama gh-pages para el sitio
